///
/// @Generated by Mockolo
///



import Combine
import Foundation
@testable import ArtGallery


class FetchGalleryMock: FetchGallery {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((Int) -> AnyPublisher<GalleryResponse, Error>)?
    func execute(_ page: Int) -> AnyPublisher<GalleryResponse, Error> {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return executeHandler(page)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

class SearchGalleryMock: SearchGallery {
    init() { }


    private(set) var executeCallCount = 0
    var executeHandler: ((String, Int) -> AnyPublisher<GalleryResponse, Error>)?
    func execute(_ query: String, _ page: Int) -> AnyPublisher<GalleryResponse, Error> {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return executeHandler(query, page)
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

class GalleryRepositoryMock: GalleryRepository {
    init() { }


    private(set) var fetchGalleryItemsCallCount = 0
    var fetchGalleryItemsHandler: ((Int) -> AnyPublisher<GalleryResponse, Error>)?
    func fetchGalleryItems(_ page: Int) -> AnyPublisher<GalleryResponse, Error> {
        fetchGalleryItemsCallCount += 1
        if let fetchGalleryItemsHandler = fetchGalleryItemsHandler {
            return fetchGalleryItemsHandler(page)
        }
        fatalError("fetchGalleryItemsHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var searchGalleryCallCount = 0
    var searchGalleryHandler: ((String, Int) -> AnyPublisher<GalleryResponse, Error>)?
    func searchGallery(_ query: String, _ page: Int) -> AnyPublisher<GalleryResponse, Error> {
        searchGalleryCallCount += 1
        if let searchGalleryHandler = searchGalleryHandler {
            return searchGalleryHandler(query, page)
        }
        fatalError("searchGalleryHandler returns can't have a default value thus its handler must be set")
    }
}

class APIServiceMock: APIService {
    init() { }


    private(set) var fetchGalleryItemsCallCount = 0
    var fetchGalleryItemsHandler: ((Int) -> AnyPublisher<GalleryResponse, Error>)?
    func fetchGalleryItems(_ page: Int) -> AnyPublisher<GalleryResponse, Error> {
        fetchGalleryItemsCallCount += 1
        if let fetchGalleryItemsHandler = fetchGalleryItemsHandler {
            return fetchGalleryItemsHandler(page)
        }
        fatalError("fetchGalleryItemsHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var searchGalleryCallCount = 0
    var searchGalleryHandler: ((String, Int) -> AnyPublisher<GalleryResponse, Error>)?
    func searchGallery(_ query: String, _ page: Int) -> AnyPublisher<GalleryResponse, Error> {
        searchGalleryCallCount += 1
        if let searchGalleryHandler = searchGalleryHandler {
            return searchGalleryHandler(query, page)
        }
        fatalError("searchGalleryHandler returns can't have a default value thus its handler must be set")
    }
}



